'use client'
import Starterpage from '@/components/Starterpage/Starterpage.jsx'
import Textani from '@/components/Starterpage/textani.jsx'
import Dots from '@/components/Starterpage/Dots.jsx'

import Head from 'next/head'

export default function Home(props) {
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Starterpage>
                <Textani word={props.randomWord} />
                <Dots numdots={3} />
            </Starterpage>
        </>
    )
}

export async function getStaticProps(context) {
    const wordList = ['Hello', 'Konnichiwa', 'Bonjour', 'Guten', 'Ciao', 'Ola', 'Marhaba', 'Nǐn hǎo']

    const randomWord = wordList[Math.floor(Math.random() * wordList.length)]

    return {
        props: { randomWord }, // will be passed to the page component as props
    };
}